osx_image: xcode10.2
language: swift
cache:
  directories:
  - Carthage
env:
  secure: ink5jhbtR9aGbiVzcrPP+jBLtYKmZ61uxmXmqwqsyAZip2zbL/tktXdLaeNhUnlJHazZF156rOFe5DFSElFmNYvpSZrXJCVMxwWKB+MJWQ879LUk6W4W65jTvkXKZmMrrUqwkOTNNMq0ycfs5tx+eFJBzHd3Z93OX0oKwb44ZjC1NC05LGJfOlZQs+7IWYKXu0XKpZ/Zo+n4jGxMPEaQCMifz8ac8WVAgsgXs5R3ANrAd6AtBHZqNLu+NzGi5FQ2u7M1EERWo69qAmmHQYKB9aYyERi4cU6KD3XF8B89szR3pH41avfYFs+ZqenF7yAm0dN5UoLBqHA5s+yBQ1kzZbvcCunEU88XjgeRuzwTUfyTq8RIN+BNzaAwSCgu/fNMaFLOZjYAXK+gtVm2elx69maC6N+hKpZblmgUtmaOQyXzY3pVNXdqCqqqzIrqSyvqPuuNSzLxjVFJUW8ycYEfB4Iywcwl74IlxWJ58WpeCgMW3cVE4l4kxw+ZWoVniumpVlp69QtgwHloUosOzmzoIwLjgEm6uGZvr3DIKKXwLZACtq8Oj7uhm8iNV4sU5eS0w+b+VC6gYCxI4yOZHWhwtBG4QtrKlEvXC0Gjy4rIXN0JuKiAHLZKiCr0YuCmks2xXv2INNnJAIBVlJ7URVY4OSY+eqCiWUSobO8n48Zu7gk=
before_install:
- gem install slather
- gem install cocoapods
- brew update
- brew outdated carthage || brew upgrade carthage
- carthage bootstrap --platform iOS --cache-builds
before_deploy:
- carthage build --no-skip-current --platform iOS --cache-builds
- carthage archive $FRAMEWORK_NAME
after_deploy:
- pod trunk push --skip-import-validation --skip-tests --allow-warnings
script:
- set -o pipefail && xcodebuild test -scheme Base58Swift -destination 'platform=iOS
  Simulator,name=iPhone XS,OS=12.2' ONLY_ACTIVE_ARCH=YES | xcpretty
after_success:
- slather
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  api_key:
    secure: MWmyQzv+FpXYJ6xapvcGv+TS0RI12uwQsFb0ncEMT6Aq4aGMrR6R2ZCdumB8rvaWk6wS5R4UtBF4f2EkHKuuVsn14A4ru9GJ7spupjFRDsHQQwP3s8NTBeSd6dMGb2KRa2ougEQtpbftiI7CqE5bVTBbOXsfekIwcTHm9m3Q3RhbayMNG4J42EdbCNLFicXo0ROYEMWfsmtKk+M2jboDw7E8UqiCgbqA75hRGOvqXqYXkd2dylgaoqGqXV1D994W5g+Iz2OJuswVXAxaFg4F0B0hFk9N52Xj2m0sxymfS7he/yiU/cOgxbzmMAh2mxwVDDQAg/uCVBCL1f8rjq/KAVyPsJYjvdDEADQ7oholCtwKj6QiLwuv7KOAnC4t9ud2qNjQaLIJD1jrtMxzHpCLpyoLMoZT0F7Ms5GwG/PC99Lo9QNpySX+qWLVZ0GOXLq6FF2bpF9SjJGVZiBFyyzXjJdNmAdfIE7daR4GqnMNTFjNm08nbGrFZWeVTN3MGo1i5No+s+Bc2yGIBhC4eGT8iW9sSixeR72nfpc718O00sIMAP69+r4YTTuvGL96i1Pn/fCMJNc2C18KRD8kv/tzpfCHSA66MIJ+OcDtnV93foYp6LfD4Ouyf5ZdTVw/65T9vtTRxeX+0uJJ8EY6UC9i19gDzSaowFMobGdH6e4fhF0=
  file: "$FRAMEWORK_NAME.framework.zip"
  skip_cleanup: true
  on:
    repo: keefertaylor/Base58Swift
    tags: true